(defun url-encode-string (str &optional encoding)
  (let ((encoding (or encoding 'utf-8)))
    (url-hexify-string (encode-coding-string str encoding))))

(defun url-decode-string (str &optional encoding)
  (let ((encoding (or encoding 'utf-8)))
    (decode-coding-string (url-unhex-string str) encoding)))

(defun url-decode-region (beg end)
  (interactive "r")
  (let ((pos beg)
        (str (buffer-substring beg end)))
    (goto-char beg)
    (delete-region beg end)
    (insert (url-decode-string str 'utf-8))))

(defun url-encode-region (beg end)
  (interactive "r")
  (let ((pos beg)
        (str (buffer-substring beg end)))
    (goto-char beg)
    (delete-region beg end)
    (insert (url-encode-string str 'utf-8))))
