;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        smarter-move-beginning-of-line
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        mc/mark-next-lines
        mc/mark-previous-lines
        smex
        vim-region-quit
        ))
